insert into Menu values(100,'Tacobell','Burritos',150);
insert into Menu values(101,'Tacobell','Tacos',250);
insert into Menu values(102,'Tacobell','Tomato Salsa',300);

insert into Menu values(103,'Nachos and Tacos','Guacamole',240);
insert into Menu values(104,'Nachos and Tacos','Enchiladas',180);
insert into Menu values(105,'Nachos and Tacos','Burritos',200);

insert into Menu values(106,'Boho','Tacos',180);
insert into Menu values(107,'Boho','Guacamole',300);
insert into Menu values(108,'Boho','Tomato Salsa',250);

insert into Menu values(109,'Hammered','Burritos',200);
insert into Menu values(110,'Hammered','Guacamole',150);
insert into Menu values(111,'Hammered','Tacos',200);

insert into Menu values(112,'Chianti','Tacos',150);
insert into Menu values(113,'Chianti','Burritos',100);
insert into Menu values(114,'Chianti','Guilt free chilli',150);

insert into Menu values(115,'Echoes','Guilt free chilli',200);
insert into Menu values(116,'Echoes','Guacamole',250);
insert into Menu values(117,'Echoes','Tacos',200);

insert into Menu values(118,'Rasta Cafe','Burritos',200);
insert into Menu values(119,'Rasta Cafe','Tacos',200);
insert into Menu values(120,'Rasta Cafe','Enchiladas',200);

insert into Menu values(121,'Leon Grill','Tacos',200);
insert into Menu values(122,'Leon Grill','Enchiladas',250);
insert into Menu values(123,'Leon Grill','Burritos',200);

insert into Menu values(124,'Go Native','Guilt free chilli',150);
insert into Menu values(125,'Go Native','Guacamole',250);
insert into Menu values(126,'Go Native','Tacos',300);

insert into Menu values(127,'CTR','Tacos',200);
insert into Menu values(128,'CTR','Enchiladas',300);
insert into Menu values(129,'CTR','Burritos',150);

insert into Menu values(130,'Brewsky','Burger',150);
insert into Menu values(131,'Brewsky','Sandwich',120);
insert into Menu values(132,'Brewsky','Soup',90);

insert into Menu values(133,'Hoot','Burger',120);
insert into Menu values(134,'Hoot','Sizzler',250);
insert into Menu values(135,'Hoot','Sandwich',140);

insert into Menu values(136,'Indigo','Salad',180);
insert into Menu values(137,'Indigo','Burger',180);
insert into Menu values(138,'Indigo','Soup',120);

insert into Menu values(139,'Hangover','Salad',250);
insert into Menu values(140,'Hangover','Sandwich',180);
insert into Menu values(141,'Hangover','Burger',220);

insert into Menu values(142,'Tipsy Bull','Salad',180);
insert into Menu values(143,'Tipsy Bull','Burger',240);
insert into Menu values(144,'Tipsy Bull','Sandwich',200);

insert into Menu values(145,'Jalsa','Soup',100);
insert into Menu values(146,'Jalsa','Burger',150);
insert into Menu values(147,'Jalsa','Salad',170);

insert into Menu values(148,'Smoor','Salad',200);
insert into Menu values(149,'Smoor','Soup',180);
insert into Menu values(150,'Smoor','Burger',220);

insert into Menu values(151,'MISU','Sizzler',270);
insert into Menu values(152,'MISU','Sandwich',120);
insert into Menu values(153,'MISU','Burger',170);

insert into Menu values(154,'Tippler','Sizzler',250);
insert into Menu values(155,'Tippler','Sandwich',150);
insert into Menu values(156,'Tippler','Salad',180);

insert into Menu values(157,'Plan B','Salad',160);
insert into Menu values(158,'Plan B','Sizzler',280);
insert into Menu values(159,'Plan B','Burger',120);

insert into Menu values(160,'Truffles','Pasta',320);
insert into Menu values(161,'Truffles','Lasagna',350);
insert into Menu values(162,'Truffles','Pizza',420);

insert into Menu values(163,'Toit','Lasagna',320);
insert into Menu values(164,'Toit','Gelato',220);
insert into Menu values(165,'Toit','Tiramisu',200);

insert into Menu values(166,'Stories','Pizza',320);
insert into Menu values(167,'Stories','Gelato',250);
insert into Menu values(168,'Stories','Pasta',250);

insert into Menu values(169,'Hakuna Matata','Lasagna',400);
insert into Menu values(170,'Hakuna Matata','Tiramisu',250);
insert into Menu values(171,'Hakuna Matata','Gelato',250);

insert into Menu values(172,'Onesta','Pizza',200);
insert into Menu values(173,'Onesta','Lasagna',300);
insert into Menu values(174,'Onesta','Gelato',200);

insert into Menu values(175,'Shiro','Pizza',250);
insert into Menu values(176,'Shiro','Pasta',300);
insert into Menu values(177,'Shiro','Lasagna',350);

insert into Menu values(178,'Shift','Tiramisu',200);
insert into Menu values(179,'Shift','Pasta',300);
insert into Menu values(180,'Shift','Pizza',250);

insert into Menu values(181,'Dominos','Pizza',350);
insert into Menu values(182,'Dominos','Pasta',250);
insert into Menu values(183,'Dominos','Lasagna',450);

insert into Menu values(184,'Roots','Pizza',250);
insert into Menu values(185,'Roots','Tiramisu',200);
insert into Menu values(186,'Roots','Lasagna',350);


insert into Menu values(187,'Dive','Gelato',150);
insert into Menu values(188,'Dive','Tiramisu',200);
insert into Menu values(189,'Dive','Pasta',250);

insert into Menu values(190,'Communiti','Roti',50);
insert into Menu values(191,'Communiti','Gulab Jamun',120);
insert into Menu values(192,'Communiti','Dal Tadka',150);

insert into Menu values(193,'Social','Paneer Masala',150);
insert into Menu values(194,'Social','Butter Naan',80);
insert into Menu values(195,'Social','Biryani',250);

insert into Menu values(196,'LOFT38','Roti',40);
insert into Menu values(197,'LOFT38','Dal Tadka',180);
insert into Menu values(198,'LOFT38','Paneer Masala',140);

insert into Menu values(199,'Farzi Cafe','Biryani',350);
insert into Menu values(200,'Farzi Cafe','Butter Naan',120);
insert into Menu values(201,'Farzi Cafe','Kadai Paneer',180);


insert into Menu values(202,'Ebony','Dal Tadka',180);
insert into Menu values(203,'Ebony','Gulab Jamun',150);
insert into Menu values(204,'Ebony','Roti',80);

insert into Menu values(205,'Paradise','Biryani',280);
insert into Menu values(206,'Paradise','Kabab',250);
insert into Menu values(207,'Paradise','Haleem',200);


insert into Menu values(208,'Nagarjuna','Butter Naan',80);
insert into Menu values(209,'Nagarjuna','Meals',150);
insert into Menu values(210,'Nagarjuna','Gongura',120);

insert into Menu values(211,'Rural Blues','Biryani',220);
insert into Menu values(212,'Rural Blues','Lassi',100);
insert into Menu values(213,'Rural Blues','Jalebi',50);

insert into Menu values(214,'1522','Kabab',200);
insert into Menu values(215,'1522','Meals',250);
insert into Menu values(216,'1522','Dal Tadka',150);


insert into Menu values(217,'RockSalt','Haleem',190);
insert into Menu values(218,'RockSalt','Butter Naan',90);
insert into Menu values(219,'RockSalt','Gulab Jamun',150);

insert into Menu values(220,'Wangs Kitchen','Noodles',250);
insert into Menu values(221,'Wangs Kitchen','Fried Rice',200);
insert into Menu values(222,'Wangs Kitchen','Manchurian',150);


insert into Menu values(223,'Mainland China','Dumplings',200);
insert into Menu values(224,'Mainland China','Fried Rice',220);
insert into Menu values(225,'Mainland China','Kung Pao',150);

insert into Menu values(226,'Crawl Street','Momos',180);
insert into Menu values(227,'Crawl Street','Noodles',280);
insert into Menu values(228,'Crawl Street','Manchurian',200);

insert into Menu values(229,'Skyye','Fried Rice',380);
insert into Menu values(230,'Skyye','Noodles',400);
insert into Menu values(231,'Skyye','Kung Pao',380);

insert into Menu values(232,'Float','Dumplings',150);
insert into Menu values(233,'Float','Manchurian',180);
insert into Menu values(234,'Float','Spring Roll',120);

insert into Menu values(235,'Zee5','Kung Pao',250);
insert into Menu values(236,'Zee5','Noodles',280);
insert into Menu values(237,'Zee5','Spring Roll',150);

insert into Menu values(238,'Fava','Fried Rice',220);
insert into Menu values(239,'Fava','Noodles',250);
insert into Menu values(240,'Fava','Momos',180);

insert into Menu values(241,'Bahar Cafe','Noodles',250);
insert into Menu values(242,'Bahar Cafe','Fried Rice',200);
insert into Menu values(243,'Bahar Cafe','Dumplings',150);

insert into Menu values(244,'Barleyz','Momos',120);
insert into Menu values(245,'Barleyz','Spring Roll',180);
insert into Menu values(246,'Barleyz','Fried Rice',220);

insert into Menu values(247,'Glocal','Noodles',250);
insert into Menu values(248,'Glocal','Fried Rice',200);
insert into Menu values(249,'Glocal','Dumplings',170);