insert into Restaurant values('Tacobell','Whitefield',9587432597,'Mexican','N');
insert into Restaurant values('Nachos and Tacos','Whitefield',9574433697,'Mexican','N');
insert into Restaurant values('Brewsky','Whitefield',9787432652,'Continental','V');
insert into Restaurant values('Hoot','Whitefield',9589832565,'Continental','N');
insert into Restaurant values('Truffles','Whitefield',8579933698,'Italian','N');
insert into Restaurant values('Toit','Whitefield',9787982657,'Italian','V');
insert into Restaurant values('Communiti','Whitefield',9587982598,'Indian','N');
insert into Restaurant values('Social','Whitefield',7574875697,'Indian','N');
insert into Restaurant values('Wangs Kitchen','Whitefield',9787432678,'Chinese','V');
insert into Restaurant values('Mainland China','Whitefield',7588852565,'Chinese','N');

insert into Restaurant values('Boho','Indiranagar',9587652597,'Mexican','N');
insert into Restaurant values('Hammered','Indiranagar',8074433697,'Mexican','N');
insert into Restaurant values('Indigo','Indiranagar',9787432652,'Continental','V');
insert into Restaurant values('Hangover','Indiranagar',9589812365,'Continental','N');
insert into Restaurant values('Stories','Indiranagar',8912533698,'Italian','N');
insert into Restaurant values('Hakuna Matata','Indiranagar',9787982657,'Italian','V');
insert into Restaurant values('LOFT38','Indiranagar',9589872598,'Indian','N');
insert into Restaurant values('Farzi Cafe','Indiranagar',9764871597,'Indian','N');
insert into Restaurant values('Crawl Street','Indiranagar',9787976678,'Chinese','V');
insert into Restaurant values('Skyye','Indiranagar',7588487565,'Chinese','N');

insert into Restaurant values('Chianti','Jaynagar',9587992597,'Mexican','N');
insert into Restaurant values('Echoes','Jaynagar',8074873697,'Mexican','N');
insert into Restaurant values('Tipsy Bull','Jaynagar',9787436552,'Continental','V');
insert into Restaurant values('Jalsa','Jaynagar',9589812399,'Continental','N');
insert into Restaurant values('Onesta','Jaynagar',8912533674,'Italian','N');
insert into Restaurant values('Shiro','Jaynagar',9877982657,'Italian','V');
insert into Restaurant values('Ebony','Jaynagar',9589815598,'Indian','N');
insert into Restaurant values('Paradise','Jaynagar',9124871597,'Indian','N');
insert into Restaurant values('Float','Jaynagar',9733976678,'Chinese','V');
insert into Restaurant values('Zee5','Jaynagar',7585587565,'Chinese','N');


insert into Restaurant values('Rasta Cafe','HSR',7487992597,'Mexican','N');
insert into Restaurant values('Leon Grill','HSR',8074847697,'Mexican','N');
insert into Restaurant values('Smoor','HSR',8587436552,'Continental','V');
insert into Restaurant values('MISU','HSR',9589812859,'Continental','N');
insert into Restaurant values('Shift','HSR',8912123674,'Italian','N');
insert into Restaurant values('Dominos','HSR',9877981257,'Italian','V');
insert into Restaurant values('Nagarjuna','HSR',9583315598,'Indian','N');
insert into Restaurant values('Rural Blues','HSR',9144871597,'Indian','N');
insert into Restaurant values('Fava','HSR',9739876678,'Chinese','V');
insert into Restaurant values('Bahar Cafe','HSR',7585587587,'Chinese','N');


insert into Restaurant values('Go Native','Majestic',7487992547,'Mexican','N');
insert into Restaurant values('CTR','Majestic',8074847658,'Mexican','N');
insert into Restaurant values('Tippler','Majestic',8587433252,'Continental','V');
insert into Restaurant values('Plan B','Majestic',9589812898,'Continental','N');
insert into Restaurant values('Roots','Majestic',8912123611,'Italian','N');
insert into Restaurant values('Dive','Majestic',9877955257,'Italian','V');
insert into Restaurant values('1522','Majestic',9598315598,'Indian','N');
insert into Restaurant values('RockSalt','Majestic',9149971597,'Indian','N');
insert into Restaurant values('Barleyz','Majestic',9739876663,'Chinese','V');
insert into Restaurant values('Glocal','Majestic',7585587457,'Chinese','N');




